[build]
command="yarn run build"
publish="build"

[build.environment]
    CI = "false"

[[redirects]]
    from = "/api/*"
    to = "https://lulzsec-tulahack-api-server.herokuapp.com/api/*"
    status = 200
    force = true # COMMENT: ensure that we always redirect
    headers = {X-From = "Netlify"}

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
